### ISSUE TITLE
garlic dying with GSL error

### ISSUE THREAD

**Issue by prnakka** [szpiech/garlic#1]
Hello! I'm trying to run GARLIC and it dies with the following error pretty frequently: 

gsl: brent.c:74: ERROR: endpoints do not straddle y=0
Default GSL error handler invoked.

Any suggestions about why this might be happening or how to fix it would be greatly appreciated.  For reference, I've pasted the command I'm using to run GARLIC below.  Thanks for your help!

~/scripts/garlic-master/bin/linux/garlic --tped subset10.tped --tfam subset10.tfam --out subset10 --error 0.001 --winsize 60 --lod-cutoff 3.992 --freq-file freqs.frq --centromere centromeres.txt

Best, 
Priya

**Comment by szpiech** [comment]
Hi Priya,

I find that this happens when the GMM portion of the code fails to find well-separated gaussians when modeling the length distribution, and thus the software has trouble determining the length-class boundary breakpoints. This can happen when the number of samples given to garlic is low. If you are splitting your data into separate runs, then I recommend taking one set of length-boundaries and providing them on the command line for the other runs. If this is your only set of data, you'll probably just have to choose your own boundaries.  Hope this helps.

-Zach

**Comment by szpiech** [comment]
Priya, It also occurs to me that you might choose to set the number of length clusters to 2, using ```--nclust 2```. That could possibly fix the error if the model fits better.

**Comment by prnakka** [comment]
Hi! Thank you for the suggestions! I tried changing the window size to be
automatically chosen (instead of specifying 60 SNPs) and that fixed the
issue.

Thanks,
Priya

**Comment by szpiech** [comment]
Great!
